import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  integrations: [tailwind(), sitemap()],
  site: 'https://motelcoach.com.au',
  trailingSlash: 'always',
  output: 'static',
  redirects: {
    '/motel-operational-review': '/operational-performance-audit/',
    '/learn-motel-mangement': '/motel-management-training-course/',
    '/motel-marketing-review': '/motel-marketing/',
    '/motel-room-pick-up': '/blog/what-is-motel-room-pick-up/',
    '/motel-resources': '/',
    '/faq': '/',
    '/cart': '/',
    '/store': '/',
    '/blog/motel-room-inventory-management-guide': '/blog/managing-motel-room-inventory/',
    '/blog/learn-guestpoint-pms-training': '/blog/free-online-guestpoint-training/',
    '/blog/test-page-load-motel': '/blog/hotel-motel-website-speed/',
    '/improve-motel-occupancy': '/blog/improve-motel-occupancy/',
    '/what-does-a-motel-manager-do': '/blog/what-does-a-motel-manager-do/',
    '/home': '/',
    '/contact-1': '/contact/',
    '/motel-websites-design': '/motel-website-design/',
    '/blog/how-tripadvisor-rankings-calculated-67c6s': '/blog/how-tripadvisor-rankings-calculated/',
    '/blog/managing-motel-room-inventory-dbjab': '/blog/managing-motel-room-inventory/',
    '/hospitality-coaching': '/motel-consultancy/',
    '/hospitality-management': '/motel-management/',
    '/how-to-run-a-motel': '/motel-management/',
    '/motel-front-desk-quick-reference-guide': '/motel-management/',
    '/how-to-manage-a-small-motel': '/motel-management/',
    '/how-to-manage-a-small-motel-1': '/motel-management/',
    '/how-to-manage-a-small-motel-1-1': '/motel-management/',
    '/motel-management-blog/category/GuestPoint+PMS': '/blog/free-online-guestpoint-training/',
    '/motel-management-blog/category/Motel+Management': '/motel-management/',
    '/motel-management-blog/tag/Reception': '/blog/',
    '/motel-management-blog/motel-room-rate-calculator': '/blog/motel-room-rate-calculator/',
    '/motel-management-blog/tag/Check-in': '/blog/front-desk-training-checklist/',
    '/motel-management-blog/tag/Legal': '/blog/',
    '/motel-management-blog/free-online-guestpoint-training': '/blog/free-online-guestpoint-training/',
    '/motel-management-blog/category/GuestPoint': '/blog/free-online-guestpoint-training/',
    '/motel-management-blog/category/Marketing': '/blog/',
    '/motel-management-blog/tag/Inventory+Management': '/blog/managing-motel-room-inventory/',
    '/motel-management-blog/tag/GuestPoint+PMS': '/blog/',
    '/motel-management-blog/hiring-housekeepers-as-contractors': '/blog/hiring-housekeepers-as-contractors/',
    '/motel-management-blog/category/Front+Desk': '/blog/',
    '/store/p/essential-guide-to-motel-management': '/motel-management-book/',
    '/motel-management-blog/tag/Hiring+Housekeepers': '/blog/hiring-housekeepers-as-contractors/',
    '/motel-management-books/p/the-essential-guide-to-motel-management-digital-edition': '/motel-management-book/',
    '/motel-management-blog/category/Revenue+Management': '/blog/',
    '/motel-management-blog/category/Expedia': '/blog/',
    '/store/p/the-essential-guide-to-motel-management-digital-edition': '/motel-management-book/',
    '/motel-management-blog/front-desk-training-checklist': '/blog/front-desk-training-checklist/',
    '/store/motel-management': '/motel-management/',
    '/motel-management-blog/tag/GuestPoint': '/blog/',
    '/motel-management-blog/motel-management-basics': '/blog/motel-management-basics/',
    '/motel-management-blog/category/Staffing': '/blog/',
    '/motel-management-blog/category/Housekeeping': '/motel-management/',
    '/motel-management-blog/category/GDS': '/motel-management/',
    '/motel-management-blog/learn-guestpoint-pms-training': '/blog/free-online-guestpoint-training/',
    '/motel-management-blog/Blog Post Title One-zd2kp-rktlj': '/blog/front-desk-training-checklist/',
    '/store/p/how-to-manage-a-small-motel': '/motel-management/',
    '/introduction-motel-mangement': '/motel-management-training-course/',
    '/motel-management-course': '/motel-management-training-course/',
    '/-motel-courses': '/courses/',
    '/motel-management-books-Wrmc2': '/motel-management-book/',
    '/motel-management-blog/optimize-bookingdotcom-for-more-bookings': '/blog/booking-review-rank/',
    '/blog/optimize-bookingdotcom-for-more-bookings': '/blog/booking-review-rank/',
    '/motel-management-blog/guestpoint-pms-account-troublshooting': '/blog/guestpoint-pms-account-troublshooting/',
    '/motel-management-blog/motel-maintenance-schedule': '/blog/motel-maintenance-schedule/',
    '/motel-management-blog/learn-google-hotel-ads': '/blog/learn-google-hotel-ads/',
    '/motel-management-blog/increase-bookingdotcom-rank-checklist': '/blog/booking-review-rank/',
    '/blog/Blog-Post-Title-One-zd2kp-rktlj': '/blog/front-desk-training-checklist/',
    '/front-desk-training-guide-motel': '/blog/front-desk-training-checklist/'
  }
});
