import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
  integrations: [tailwind(), sitemap()],
  site: 'https://motelcoach.com.au',

  redirects: {
    '/hospitality-coaching': '/motel-consultancy',
    '/hospitality-courses-australia': '/motel-management-training-course',
    '/hospitality-diplomas-degrees-australia': '/motel-management-training-course',
    '/hospitality-management': '/motel-management',
    '/hospitality-training-australia': '/motel-management-training-course',
    '/motel-room-pick-up': '/blog/what-is-motel-room-pick-up',
    '/how-to-run-a-motel': '/motel-management',
    '/motel-front-desk-quick-reference-guide': '/motel-management',
    '/how-to-manage-a-small-motel': '/motel-management',
    '/motel-management-book-free-shortened': '/motel-management-book',
    '/learn-motel-mangement': '/motel-management-training-course',
    '/motel-marketing-review': '/motel-marketing',
    '/motel-management-australia': '/motel-management',
    '/motel-management-blog': '/blog',
    '/blog/test-page-load-motel': '/blog/hotel-motel-website-speed',
    '/improve-motel-occupancy-1': '/motel-consultancy',
    '/blog/motel-marketing-course-yx5mj': '/blog/motel-marketing-checklist',
    '/blog/Blog-Post-Title-One-zd2kp-rktlj': '/blog/front-desk-training-checklist',
    '/blog/motel-front-desk-checklist': '/blog/front-desk-training-checklist',
    '/motel-management-books-Wrmc2': '/motel-management-books',
    '/motel-operational-review': '/motel-consultancy',
    '/blog/motel-marketing-course': '/blog/motel-marketing-basics',
    '/managing-motel-room-inventory-dbjab': '/blog/motel-management-21-day-transition-strategy',
    '/blog/front-desk-training-hospitality': '/blog/front-desk-training-checklist',
    '/blog/hospitality-careers-getting-started': '/blog/motel-manager-career',
    '/blog/motel-manager-duties': '/blog/motel-manager-career',
    '/blog/a-day-in-life-of-motel-manager': '/blog/motel-manager-career',
    '/blog/increase-bookingdotcom-rank-checklist': '/blog/booking-review-rank',
    '/blog/motel-marketing-basics': '/blog/motel-marketing-checklist',
    '/motel-receptionist-jobs': '/blog/motel-receptionist-jobs',
    '/home': '/',
    '/what-does-a-motel-manager-do': '/blog/what-does-a-motel-manager-do',
    '/improve-motel-occupancy': '/blog/improve-motel-occupancy',
    '/blog/motel-room-inventory-management-guide': '/blog/managing-motel-room-inventory',
    '/blog/optimize-bookingdotcom-for-more-bookings': '/blog/booking-review-rank',
    '/motel-management-course-purchase': '/motel-management-training-course',
    '/front-desk-training-guide-motel': '/blog/front-desk-training-checklist',
    '/motel-websites-design': '/motel-website-design',
    '/faq': '/',
    '/motel-resources': '/',
    '/blog/motel-manager-career': '/blog/what-does-a-motel-manager-do',
    '/motel-seo-guide': '/blog/motel-seo',
    '/local-seo-motels': '/blog/motel-seo',
	  '/motel-seo': '/blog/motel-seo',
    '/motel-management-blog/hiring-housekeepers-as-contractors': '/blog/hiring-housekeepers-as-contractors',
    '/motel-management-lessons?category=Booking.com': '/blog/booking-review-rank', 
    '/motel-management-blog/optimize-bookingdotcom-for-more-bookings': '/blog/booking-review-rank',
    '/motel-management-blog/motel-management-blog/motel-room-inventory-management-guide': '/blog/booking-review-rank',
    '/motel-management-blog/tag/Reception': '/blog/', 
    '/how-to-manage-a-small-motel-1-1': '/motel-management',
    '/motel-management-blog/category/Staffing': '/blog',
    '/motel-management-lessons?category=Housekeeping': '/blog',
    '/motel-management-blog/front-desk-training-checklist': '/blog',
    '/store/p/the-essential-guide-to-motel-management-digital-edition': '/motel-management-book',
    '/motel-management-blog/category/Motel+Management': '/blog',
    '/motel-management-lessons?category=Maintenance': '/blog',
    '/motel-management-blog/category/Booking.com': '/blog',
    '/motel-management-course': '/motel-management-training-course',
    '/motel-management-blog/learn-google-hotel-ads': '/blog/learn-google-hotel-ads',
    '/motel-management-blog/motel-room-rate-calculator': '/blog/motel-room-rate-calculator',
    '/store/p/essential-guide-to-motel-management': '/motel-management-book',
    '/motel-management-blog/category/GuestPoint+PMS': '/blog',
    '/motel-management-lessons?category=Revenue Management': '/blog',
    '/motel-management-blog/tag/Check-in': '/blog',
    '/motel-management-blog/category/Marketing': '/blog',
    '/motel-management-blog/category/GDS': '/blog',
    '/motel-management-blog/increase-bookingdotcom-rank-checklist': '/blog',
    '/motel-management-lessons?category=Motel Management': '/blog',
    '/motel-management-blog/test-page-load-motel': '/blog',
    '/store': '/',
    '/motel-management-blog/test-page-load-motel': '/blog',
    '/motel-management-blog/tag/GuestPoint': '/blog',
    '/motel-management-blog/free-online-guestpoint-training': '/blog/free-online-guestpoint-training',
    '/store/motel-management': '/',
    '/motel-management-blog/tag/PMS': '/blog',
    '/motel-management-lessons?category=Financial': '/blog',
    '/motel-management-blog/category/Housekeeping': '/blog',
    '/motel-management-blog/tag/Legal': '/blog',
    '/motel-management-blog/category/Revenue+Management': '/blog',
    '/motel-management-blog/tag/GuestPoint+PMS': '/blog',
    '/motel-management-blog/category/Front+Desk': '/blog',
    '/motel-management-blog/category/Expedia': '/blog',
    '/motel-management-blog/Blog Post Title One-zd2kp-rktlj': '/blog',
    '/motel-management-blog/tag/Inventory+Management': '/blog',
    '/motel-management-blog/learn-guestpoint-pms-training': '/blog/free-online-guestpoint-training',
    '/motel-management-blog/tag/Hiring+Housekeepers': '/blog/hiring-housekeepers-as-contractors',
    '/motel-management-books/p/the-essential-guide-to-motel-management-digital-edition': '/motel-management-book',
    '/motel-marketing-strategies-for-independent-operators-increase-direct-bookings-occupancy': '/motel-marketing',
    '/motel-management-lessons?category=Expedia': '/blog',
    '/motel-management-blog/category/GuestPoint': '/blog',
    '/motel-management-blog/guestpoint-pms-account-troublshooting': '/blog/guestpoint-pms-account-troubleshooting'
  },
});
